"use strict";
const DB_NAME="TudoDeHelenaDB",DB_VERSION=1;let db,state={products:[],rentals:[],rentalItems:[],photo:null,rentalFilter:"active"},installPrompt=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(n||0)),fmtDate=v=>v?new Date(v+"T12:00:00").toLocaleDateString("pt-BR"):"—";
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2),norm=s=>(s||"").trim().toLocaleLowerCase("pt-BR");
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains("products"))d.createObjectStore("products",{keyPath:"id"});if(!d.objectStoreNames.contains("rentals"))d.createObjectStore("rentals",{keyPath:"id"})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function store(name,mode="readonly"){return db.transaction(name,mode).objectStore(name)}
function all(name){return new Promise((res,rej)=>{const r=store(name).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function put(name,val){return new Promise((res,rej)=>{const r=store(name,"readwrite").put(val);r.onsuccess=()=>res(val);r.onerror=()=>rej(r.error)})}
function del(name,id){return new Promise((res,rej)=>{const r=store(name,"readwrite").delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clearStore(name){return new Promise((res,rej)=>{const r=store(name,"readwrite").clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function refresh(){state.products=await all("products");state.rentals=await all("rentals");renderAll()}
function rentedQty(id){return state.rentals.filter(r=>r.status==="active").reduce((s,r)=>s+(r.items||[]).filter(i=>i.productId===id).reduce((a,i)=>a+Number(i.qty||0),0),0)}
function available(p){return Math.max(0,Number(p.qty||0)-rentedQty(p.id))}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2600)}
function go(view){const titles={dashboard:"Visão geral",products:"Estoque",rentals:"Locações",backup:"Backup"};$$(".view").forEach(v=>v.classList.toggle("active",v.id==="view-"+view));$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("#pageTitle").textContent=titles[view]||"Tudo de Helena";if(view==="products")renderProducts();if(view==="rentals")renderRentals();window.scrollTo({top:0,behavior:"smooth"})}
function renderAll(){renderDashboard();renderProducts();renderRentals();fillProductOptions()}
function renderDashboard(){const units=state.products.reduce((s,p)=>s+Number(p.qty||0),0),rent=state.products.reduce((s,p)=>s+rentedQty(p.id),0),ret=state.products.reduce((s,p)=>s+Number(p.past||0)*Number(p.price||0),0);$("#statModels").textContent=state.products.length;$("#statAvailable").textContent=Math.max(0,units-rent);$("#statRented").textContent=rent;$("#statReturn").textContent=money(ret);
 const active=state.rentals.filter(r=>r.status==="active").sort((a,b)=>(a.returnDate||"").localeCompare(b.returnDate||"")).slice(0,5),box=$("#dashRentals");if(!active.length){box.className="list empty";box.innerHTML="<b>♡</b><span>Nenhuma locação ativa.</span>"}else{box.className="list";box.innerHTML=active.map(r=>`<div class="list-row"><div><strong>${esc(r.client)}</strong><small>Festa: ${fmtDate(r.partyDate)} • Devolução: ${fmtDate(r.returnDate)}</small></div><span class="badge warn">${(r.items||[]).reduce((s,i)=>s+Number(i.qty||0),0)} peça(s)</span></div>`).join("")}
 const top=[...state.products].sort((a,b)=>(Number(b.past||0)*Number(b.price||0))-(Number(a.past||0)*Number(a.price||0))).slice(0,5),tb=$("#dashTop");if(!top.length){tb.className="list empty";tb.innerHTML="<b>☆</b><span>Cadastre peças para acompanhar.</span>"}else{tb.className="list";tb.innerHTML=top.map((p,i)=>`<div class="list-row"><div><strong>#${i+1} ${esc(p.name)}</strong><small>${Number(p.past||0)} locação(ões)</small></div><strong>${money(Number(p.past||0)*Number(p.price||0))}</strong></div>`).join("")}}
function renderProducts(){const q=norm($("#productSearch")?.value),filter=$("#productFilter")?.value||"all";let list=state.products.filter(p=>!q||norm(p.name).includes(q)||norm(p.category).includes(q));if(filter==="available")list=list.filter(p=>available(p)>0);if(filter==="rented")list=list.filter(p=>rentedQty(p.id)>0);const box=$("#productsGrid");if(!list.length){box.innerHTML=`<div class="empty-card"><div><b>▣</b><strong>Nenhuma peça encontrada</strong><p>Cadastre a primeira peça do acervo ou altere a busca.</p></div></div>`;return}box.innerHTML=list.sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")).map(p=>{const av=available(p),rq=rentedQty(p.id),status=av>0?`<span class="badge ok">Disponível: ${av}</span>`:`<span class="badge warn">Sem disponibilidade</span>`;return `<article class="product-card"><div class="product-photo">${p.photo?`<img src="${p.photo}" alt="${esc(p.name)}">`:`<div class="placeholder">✦</div>`}<div class="status-float">${status}</div></div><div class="product-body"><h3>${esc(p.name)}</h3><span class="category">${esc(p.category||"Sem categoria")}</span><div class="product-meta"><div><span>Total</span><strong>${p.qty}</strong></div><div><span>Locadas</span><strong>${rq}</strong></div><div><span>Valor</span><strong>${money(p.price)}</strong></div></div><div class="product-actions"><button class="mini-btn rent" data-rent-product="${p.id}" ${av<=0?"disabled":""}>♡ Locar produto</button><button class="mini-btn" data-edit-product="${p.id}">Editar</button><button class="mini-btn danger" data-delete-product="${p.id}">Excluir</button></div></div></article>`}).join("")}
function renderRentals(){let list=[...state.rentals];if(state.rentalFilter==="active")list=list.filter(r=>r.status==="active");if(state.rentalFilter==="finished")list=list.filter(r=>r.status==="finished");list.sort((a,b)=>(b.partyDate||"").localeCompare(a.partyDate||""));const box=$("#rentalsList");if(!list.length){box.innerHTML=`<div class="empty-card"><div><b>♡</b><strong>Nenhuma locação aqui</strong><p>Crie uma nova locação para reservar peças para um cliente.</p></div></div>`;return}box.innerHTML=list.map(r=>{const total=(r.items||[]).reduce((s,i)=>s+Number(i.price||0)*Number(i.qty||0),0),names=(r.items||[]).map(i=>{const p=state.products.find(p=>p.id===i.productId);return `${Number(i.qty)}× ${esc(p?.name||i.name||"Peça")}`}).join(" • ");return `<article class="rental-card"><div class="rental-head"><div><h3>${esc(r.client)}</h3><small>${esc(r.phone||"Sem telefone")}</small></div><span class="badge ${r.status==="active"?"warn":"ok"}">${r.status==="active"?"Em andamento":"Finalizada"}</span></div><div class="rental-info"><div><span>Festa</span><strong>${fmtDate(r.partyDate)}</strong></div><div><span>Retirada</span><strong>${fmtDate(r.pickupDate)}</strong></div><div><span>Devolução</span><strong>${fmtDate(r.returnDate)}</strong></div><div><span>Peças</span><strong>${(r.items||[]).reduce((s,i)=>s+Number(i.qty||0),0)}</strong></div></div><div class="rental-items-mini">${names||"Sem itens"}${r.notes?`<br>Obs.: ${esc(r.notes)}`:""}</div><div class="rental-foot"><strong>${money(total)}</strong><div>${r.status==="active"?`<button class="mini-btn" data-finish-rental="${r.id}">Confirmar devolução</button>`:""}<button class="mini-btn danger" data-delete-rental="${r.id}">Excluir</button></div></div></article>`}).join("")}
function fillProductOptions(){const dl=$("#productOptions");dl.innerHTML=state.products.filter(p=>available(p)>0).sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")).map(p=>`<option value="${escAttr(p.name)}">${available(p)} disponível(is)</option>`).join("")}
function openProduct(id=null){$("#productForm").reset();$("#productId").value="";state.photo=null;$("#photoPreview").hidden=true;$("#photoPlaceholder").hidden=false;$("#removePhoto").classList.add("hidden");$("#productDialogTitle").textContent=id?"Editar peça":"Cadastrar peça";if(id){const p=state.products.find(x=>x.id===id);if(!p)return;$("#productId").value=p.id;$("#productName").value=p.name;$("#productCategory").value=p.category||"";$("#productQty").value=p.qty;$("#productCost").value=p.cost||"";$("#productPrice").value=p.price||"";$("#productPast").value=p.past||0;$("#productNotes").value=p.notes||"";state.photo=p.photo||null;if(p.photo){$("#photoPreview").src=p.photo;$("#photoPreview").hidden=false;$("#photoPlaceholder").hidden=true;$("#removePhoto").classList.remove("hidden")}}$("#productDialog").showModal()}
function closeDialog(id){const d=$("#"+id);if(d?.open)d.close()}
function readPhoto(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>{const img=new Image();img.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",.82))};img.onerror=rej;img.src=fr.result};fr.onerror=rej;fr.readAsDataURL(file)})}
function openRental(productId=null){$("#rentalForm").reset();state.rentalItems=[];const today=new Date().toISOString().slice(0,10);$("#pickupDate").value=today;if(productId){const p=state.products.find(x=>x.id===productId);if(p&&available(p)>0)state.rentalItems.push({productId:p.id,name:p.name,qty:1,price:Number(p.price||0)})}renderRentalItems();fillProductOptions();$("#rentalDialog").showModal()}
async function pickPhoneContact(){if(!navigator.contacts?.select)return toast("A seleção de contatos não está disponível neste navegador. Digite o contato manualmente.");try{const contacts=await navigator.contacts.select(["name","tel"],{multiple:false}),c=contacts?.[0];if(!c)return;const name=Array.isArray(c.name)?c.name[0]:c.name,tel=Array.isArray(c.tel)?c.tel[0]:c.tel;if(name)$("#clientName").value=name;if(tel)$("#clientPhone").value=tel;toast("Contato selecionado.")}catch(e){if(e?.name!=="AbortError")toast("Não foi possível abrir os contatos. Você pode digitar manualmente.")}}
function addRentalItem(){const name=$("#rentalProductSearch").value.trim(),qty=Math.max(1,Number($("#rentalProductQty").value||1)),p=state.products.find(x=>norm(x.name)===norm(name));if(!p)return toast("Escolha uma peça da lista.");const already=state.rentalItems.filter(i=>i.productId===p.id).reduce((s,i)=>s+i.qty,0),av=available(p)-already;if(qty>av)return toast(`Só há ${Math.max(0,av)} unidade(s) disponível(is).`);const existing=state.rentalItems.find(i=>i.productId===p.id);if(existing)existing.qty+=qty;else state.rentalItems.push({productId:p.id,name:p.name,qty,price:Number(p.price||0)});$("#rentalProductSearch").value="";$("#rentalProductQty").value=1;renderRentalItems()}
function renderRentalItems(){const box=$("#rentalItems");if(!state.rentalItems.length)box.innerHTML='<div class="inline-empty">Nenhuma peça adicionada.</div>';else box.innerHTML=state.rentalItems.map((i,idx)=>`<div class="selected-item"><div><strong>${esc(i.name)}</strong><small>${i.qty} × ${money(i.price)} = ${money(i.qty*i.price)}</small></div><button type="button" data-remove-rental-item="${idx}" aria-label="Remover">×</button></div>`).join("");$("#rentalTotal").textContent=money(state.rentalItems.reduce((s,i)=>s+i.qty*i.price,0))}
function ask(title,msg,okLabel="Confirmar"){return new Promise(res=>{const d=$("#confirmDialog");$("#confirmTitle").textContent=title;$("#confirmMessage").textContent=msg;$("#confirmOk").textContent=okLabel;const done=v=>{d.close();$("#confirmOk").onclick=null;$("#confirmCancel").onclick=null;res(v)};$("#confirmOk").onclick=()=>done(true);$("#confirmCancel").onclick=()=>done(false);d.showModal()})}
async function exportData(){const payload={app:"Tudo de Helena Estoque",version:1,exportedAt:new Date().toISOString(),products:state.products,rentals:state.rentals},blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`Tudo_de_Helena_backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast("Backup baixado.")}
async function importData(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.products)||!Array.isArray(data.rentals))throw new Error("Formato inválido");if(!await ask("Restaurar backup?","Os dados atuais deste aparelho serão substituídos.","Restaurar"))return;await clearStore("products");await clearStore("rentals");for(const p of data.products)await put("products",p);for(const r of data.rentals)await put("rentals",r);await refresh();toast("Backup restaurado com sucesso.")}catch(e){console.error(e);toast("Não foi possível importar esse arquivo.")}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function escAttr(v){return esc(v).replace(/\n/g," ")}
document.addEventListener("click",async e=>{const b=e.target.closest("button,[data-go]");if(!b)return;if(b.dataset.view)go(b.dataset.view);if(b.dataset.go)go(b.dataset.go);if(b.hasAttribute("data-open-product"))openProduct();if(b.hasAttribute("data-open-rental"))openRental();if(b.dataset.rentProduct)openRental(b.dataset.rentProduct);if(b.dataset.close)closeDialog(b.dataset.close);if(b.dataset.editProduct)openProduct(b.dataset.editProduct);
 if(b.dataset.deleteProduct){const id=b.dataset.deleteProduct,p=state.products.find(x=>x.id===id);if(rentedQty(id)>0)return toast("Essa peça está em uma locação ativa.");if(await ask("Excluir peça?",`${p?.name||"Esta peça"} será removida do estoque.`,"Excluir")){await del("products",id);await refresh();toast("Peça excluída.")}}
 if(b.dataset.removeRentalItem!==undefined){state.rentalItems.splice(Number(b.dataset.removeRentalItem),1);renderRentalItems()}
 if(b.dataset.finishRental){const r=state.rentals.find(x=>x.id===b.dataset.finishRental);if(await ask("Confirmar devolução?",`As peças de ${r.client} voltarão a ficar disponíveis.`,"Confirmar devolução")){r.status="finished";r.finishedAt=new Date().toISOString();await put("rentals",r);for(const i of r.items||[]){const p=state.products.find(x=>x.id===i.productId);if(p){p.past=Number(p.past||0)+Number(i.qty||0);await put("products",p)}}await refresh();toast("Devolução registrada.")}}
 if(b.dataset.deleteRental){const r=state.rentals.find(x=>x.id===b.dataset.deleteRental);if(await ask("Excluir locação?",`A locação de ${r.client} será apagada.`,"Excluir")){await del("rentals",r.id);await refresh();toast("Locação excluída.")}}
 if(b.dataset.rfilter){state.rentalFilter=b.dataset.rfilter;$$("[data-rfilter]").forEach(x=>x.classList.toggle("active",x.dataset.rfilter===state.rentalFilter));renderRentals()}
});
$$("[data-open-product]").forEach(()=>{});
$("#productSearch").addEventListener("input",renderProducts);$("#productFilter").addEventListener("change",renderProducts);$("#addRentalItem").addEventListener("click",addRentalItem);$("#pickContactBtn").addEventListener("click",pickPhoneContact);$("#rentalProductSearch").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();addRentalItem()}});
$("#productPhoto").addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f)return;state.photo=await readPhoto(f);$("#photoPreview").src=state.photo;$("#photoPreview").hidden=false;$("#photoPlaceholder").hidden=true;$("#removePhoto").classList.remove("hidden")});
$("#removePhoto").addEventListener("click",()=>{state.photo=null;$("#productPhoto").value="";$("#photoPreview").hidden=true;$("#photoPlaceholder").hidden=false;$("#removePhoto").classList.add("hidden")});
$("#productForm").addEventListener("submit",async e=>{e.preventDefault();const id=$("#productId").value||uid(),old=state.products.find(x=>x.id===id),qty=Number($("#productQty").value);if(old&&qty<rentedQty(id))return toast(`Há ${rentedQty(id)} unidade(s) em locação. A quantidade total não pode ser menor.`);const p={id,name:$("#productName").value.trim(),category:$("#productCategory").value.trim(),qty,cost:Number($("#productCost").value||0),price:Number($("#productPrice").value||0),past:Number($("#productPast").value||0),notes:$("#productNotes").value.trim(),photo:state.photo,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};await put("products",p);closeDialog("productDialog");await refresh();toast(old?"Peça atualizada.":"Peça cadastrada.")});
$("#rentalForm").addEventListener("submit",async e=>{e.preventDefault();if(!state.rentalItems.length)return toast("Adicione pelo menos uma peça.");for(const i of state.rentalItems){const p=state.products.find(x=>x.id===i.productId);if(!p||i.qty>available(p))return toast(`A disponibilidade de ${p?.name||i.name} mudou. Revise a quantidade.`)}const r={id:uid(),client:$("#clientName").value.trim(),phone:$("#clientPhone").value.trim(),partyDate:$("#partyDate").value,pickupDate:$("#pickupDate").value,returnDate:$("#returnDate").value,notes:$("#rentalNotes").value.trim(),items:state.rentalItems.map(i=>({...i})),status:"active",createdAt:new Date().toISOString()};await put("rentals",r);closeDialog("rentalDialog");await refresh();go("rentals");toast("Locação salva.")});
$("#exportBtn").addEventListener("click",exportData);$("#importFile").addEventListener("change",e=>{const f=e.target.files?.[0];if(f)importData(f);e.target.value=""});$("#clearBtn").addEventListener("click",async()=>{if(await ask("Apagar tudo?","Todos os produtos, fotos e locações serão apagados deste aparelho. Faça um backup antes.","Apagar tudo")){await clearStore("products");await clearStore("rentals");await refresh();toast("Dados apagados.")}});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").addEventListener("click",async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("#installBtn").classList.add("hidden")});window.addEventListener("appinstalled",()=>toast("Tudo de Helena instalado!"));
(async()=>{try{db=await openDB();await refresh();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=4").catch(console.error)}catch(e){console.error(e);toast("Erro ao abrir o banco local.")}})();